
CREATE TABLE ORDER 

(Order_No	CHAR(10)	NOT NULL,  

Ship_Date	DATE, 

Project_No	CHAR(10)	NOT NULL, 

PRIMARY KEY (Order_No),  

FOREIGN KEY (Project_No) REFERENCES PROJECT(Project_No) ); 


CREATE TABLE PART 

(Part_No	VARCHAR(20)	NOT NULL,  

PRIMARY KEY (Part_No) ); 


CREATE TABLE VENDOR 

(Vendor_ID	INT	NOT NULL, 

Vendor_Name	VARCHAR(20)	NOT NULL, 

Phone_No	INT, 

PRIMARY KEY(Vendor_ID) ); 



CREATE TABLE EMPLOYEE 

(SSN	INT	NOT NULL, 

First_Name	VARCHAR(255)	NOT NULL, 

Last_Name	VARCHAR(255)	NOT NULL, 

DOB	DATE	NOT NULL, 

Phone_No	INT	NOT NULL, 

Email	VARCHAR(255), 

Address_Line_1		VARCHAR(255)	NOT NULL, 

Address_Line_2		VARCHAR(255), 

City			VARCHAR(255)	NOT NULL, 

Prov_State		VARCHAR(255)	NOT NULL, 

Country			VARCHAR(255)	NOT NULL, 

Postal_Zip		VARCHAR(255)	NOT NULL, 

Job_Type	VARCHAR(255), 

PRIMARY KEY(SSN) ); 


CREATE TABLE SALES_HAVE_CLIENTS 

(Sales_SSN	INT	NOT NULL, 

Client_ID	INT	NOT NULL, 

PRIMARY KEY(Sales_SSN, Client_ID),

FOREIGN KEY(Sales_SSN) REFERENCES EMPLOYEE(SSN), 

FOREIGN KEY(Client_ID) REFERENCES CLIENT(Client_ID) ); 


CREATE TABLE SALES_PROPOSALS 

(Sales_SSN	INT	NOT NULL, 

Proposal_No	INT	NOT NULL, 

PRIMARY KEY(Sales_SSN, Proposal_No),

FOREIGN KEY(Sales_SSN) REFERENCES EMPLOYEE(SSN), 

FOREIGN KEY(Proposal_No) REFERENCES CLIENT(Proposal_No) ); 



CREATE TABLE VENDORS_PROVIDES_PARTS 

(Vendor_ID	INT	NOT NULL, 

Part_No	INT	NOT NULL, 

PRIMARY KEY(Vendor_ID, Part_No),

FOREIGN KEY(Vendor_Id) REFERENCES VENDOR(Vendor_ID), 

FOREIGN KEY(Part_No) REFERENCES PART(Part_No) ); 



CREATE TABLE PURCHASE_ORDERS 

(Purchaser_SSN	INT	NOT NULL, 

Vendor_ID	INT	NOT NULL, 

Purchase_Order	VARCHAR(255)	NOT NULL, 

PRIMARY KEY (Purchaser_SSN, Vendor_ID),

FOREIGN KEY(Purchaser_SSN) REFERENCES  EMPLOYEE(SSN), 

FOREIGN KEY(Vendor_ID) REFERENCES VENDOR(Vendor_ID) ); 



CREATE TABLE LABOUR_ORDER 

(Labour_SSN	INT	NOT NULL, 

Order_No	INT	NOT NULL, 

Start_Date	DATE	NOT NULL, 

Hours	INT	NOT NULL, 

PRIMARY KEY(Labour_SSN, Order_No),

FOREIGN KEY(Labour_SSN) REFERENCES EMPLOYEE(SSN), 

FOREIGN KEY(Order_No) REFERENCES ORDER(Order_No) ); 



CREATE TABLE PARTS_INVENTORY 

(Order_No	INT	NOT NULL, 

Part_No	INT	NOT NULL, 

Qty	INT	NOT NULL, 

PRIMARY KEY(Order_No, Part_No),

FOREIGN KEY(Order_No) REFERENCES ORDER(Order_No), 

FOREIGN KEY(Part_No) REFERENCES PART(Part_No) ); 